name: Rust CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Generate documentation
        run: cargo doc --no-deps

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: target/doc

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation

      - name: Verify documentation artifact exists
        run: |
          if [ ! -d "./target/doc" ]; then
            echo "Documentation directory not found!"
            exit 1
          fi

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages || echo "No gh-pages branch found"
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Clean gh-pages directory
        run: |
          find . -mindepth 1 -not -name '.git' -exec rm -rf {} +

      - name: Copy documentation to gh-pages
        run: cp -r ./target/doc/* ./

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update documentation"
          git push origin gh-pages
