name: Rust CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation

      - name: Verify documentation artifact exists
        run: |
          if [ ! -d "./documentation" ]; then
            echo "Documentation directory not found!"
            exit 1
          fi

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages || echo "No gh-pages branch found"
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Clean gh-pages directory
        run: |
          find . -mindepth 1 -not -name '.git' -exec rm -rf {} +

      - name: Copy documentation to gh-pages
        run: cp -r ./documentation/* ./
